#pragma once

enum class Operator {
   OPERATOR_NULL,
   OPERATOR_OPEN_BRACKET,
   OPERATOR_CLOSED_BRACKET,
   OPERATOR_ABS,
   OPERATOR_FACTORIAL,
   OPERATOR_BITWISE_NOT,
   OPERATOR_EXPONENT,  // e, E
   OPERATOR_POWER,     // **
   OPERATOR_MODULO,
   OPERATOR_DIVISION,
   OPERATOR_MULTIPLICATION,
   OPERATOR_SUBTRACTION,
   OPERATOR_ADDITION,
   OPERATOR_BITWISE_SHR,
   OPERATOR_BITWISE_SHL,
   OPERATOR_BITWISE_AND,
   OPERATOR_BITWISE_XOR,
   OPERATOR_BITWISE_OR,
   OPERATOR_COMMA,
   OPERATOR_SQRT,
};
